improve iterm customization

diff --git a/script/bootstrap b/script/bootstrap
--- a/script/bootstrap
+++ b/script/bootstrap
@@ -4,6 +4,7 @@
 source ./script/prompt
 source ./functions/iterm-setup
 
+
 cd "$(dirname "$0")/.."
 DOTFILES_ROOT=$(pwd -P)
 
@@ -212,22 +213,12 @@ alex_colors () {
   sudo gem install colorls && success 'ls colors have been configured'
 }
 
-alex_itermConfig () {
-  # iterm2 config
-  read -p "Do you currently use iTerm2 and would you like to set my profile settings? y/n " -n 1 -r
-  echo ''
-  if [[ $REPLY =~ ^[Yy]$ ]]
-  then
-    iterm-setup
-  fi
-}
 
 alex_configFix () {
-
-  echo '"'
-  echo 'Fixing .config permissions'
-  echo '"'
-  
+  echo "''"
+  echo "Fixing .config permissions"
+  echo "''"
+  # .config permissions fix
   if ! [ -d "$HOME/.config" ]; then
     info "$HOME/.config doesn't exist, nothing to fix"
   else
@@ -245,16 +236,78 @@ alex_fontSetup () {
 backupBin
 alex_Symlinks
 alex_colors
-alex_itermConfig
 alex_fontSetup
+alex_itermConfig
 alex_configFix
 
 # Set zsh as default shell
-read -p "Do you want me to setup the zsh shell as your default shell? y/n " -n 1 -r
+read -p "Should I set zsh to your default shell? y/n " -n 1 -r
 echo ''
 if [[ $REPLY =~ ^[Yy]$ ]] 
   then
     chsh -s /bin/zsh
 fi
 
-success 'Badass macOS terminal installed!'
+
+alex_itermConfig () {
+
+  if ! [ -f /Applications/iTerm2 ]; 
+      then
+    else 
+
+      echo '"'
+      read -p "I see you are already using iTerm2. Do you like to try my profile settings? y/n " -n 1 -r
+      echo '"'
+      if [[ $REPLY =~ ^[Yy]$ ]]
+      then
+
+          defaults write com.googlecode.iterm2 PrefsCustomFolder -string "$HOME/.itermcfg/"
+          defaults write com.googlecode.iterm2 LoadPrefsFromCustomFolder -bool true
+
+          if [[ $? -eq 0 ]]
+          then
+              success "I could set you my preferences successfully!"
+          else
+              fail "failed to apply my settings." >&2
+          fi
+      fi
+
+    echo '"'
+    echo 'Please choose a theme: '
+    info 'If you later want to try other ones, '
+    info '>   zshtheme:   and you can choose again! '
+    echo '"'
+
+    options=("spaceship" "powerline10k" "powerlevel9k" "random")
+
+    select opt in "${options[@]}"
+    do
+        case $opt in
+            "spaceship")
+                export ZSH_THEME=$opt
+                ;;
+            "powerline10k")
+                export ZSH_THEME="$opt/$opt"
+                ;;
+            "powerlevel9k")
+                export ZSH_THEME="$opt/$opt"
+                ;;
+            "random")
+                export ZSH_THEME="random";
+                ;;
+            *) echo "invalid option $REPLY";;
+        esac
+    done
+  fi  
+}
+
+
+if ! [ -f /Applications/iTerm2 ]; 
+  then
+    success 'Badass macOS terminal installed!'
+    return 0;
+  else 
+    ./Applications/iTerm2
+    success 'Badass macOS terminal installed!'
+    return 0;
+fi
