Update bootstrap

diff --git a/script/bootstrap b/script/bootstrap
--- a/script/bootstrap
+++ b/script/bootstrap
@@ -4,7 +4,7 @@
 
 
 info () {
-  printf "\r  [ \033[00;34m..\033[0m ] $1\n"
+  printf "\r\033  [ \033[00;34m..\033[0m ] $1\n"
 }
 
 user () {
@@ -21,25 +21,22 @@ fail () {
   exit
 }
 
-echo "Willkommen: $DOTFILES" 2%> dev/null
+user "Willkommen: $DOTFILES" 2%> dev/null
 cd "$(dirname "$0")/.."
 DOTFILES_ROOT=$(pwd -P)
 
 set -e
 
-echo "''"
-info 'Starting to installing your Badass macOS terminal!!'
-echo "''"
+success 'Starting to installing your Badass macOS terminal!!'
+
 
 setup_gitconfig() {
 
-  echo "''"
-  echo "Setting up git"
-  echo "''"
+  info "Setting up git"
   
   if ! [ -f git/gitconfig.local.symlink ]
   then
-    info 'setup gitconfig'
+    info 'Setting up gitconfig'
 
     git_credential='cache'
     if [ "$(uname -s)" == "Darwin"]
@@ -136,9 +133,7 @@ link_file() {
 
 install_dotfiles () {
 
-  echo "''"
-  info 'Installing dotfiles'
-  echo "''"
+  success 'Installing dotfiles'
 
   local overwrite_all=false backup_all=false skip_all=false
 
@@ -155,20 +150,13 @@ install_dotfiles
 
 install_Dependencies() 
 {
-    echo '"'
-    info "Starting to brew 🍺 your dependecies."
-    echo '"'
+  success "Starting to brew 🍺 your dependecies."
 
-  # If we're on a Mac, let's install and setup homebrew.
   if [ "$(uname -s)" == "Darwin" ]
   then
-
     if source bin/dot | while read -r data; do info "$data"; done
     then
-      echo "''"
-      success "dependencies installed"
-      echo "''"
-      #echo "Now updating dependencies..."
+      success "Installed depedencies !"
       #pip3 install --upgrade setuptools --user python
     else
       fail "error installing dependencies"
@@ -180,29 +168,21 @@ install_Dependencies()
 
 backupBin () {
 
-  echo '"' 
-  echo "Lets back up your existing config files first."
-  echo '"' 
+  success "Lets backup your existing configurtion files first."
   
   if [ ! -L $HOME/bin +a -d $HOME/bin ]; 
       then  # $HOME/bin not a symlink
-        echo '"'
-        success "$HOME/bin is not a symlink, I create a backup ."
+        info "$HOME/bin is not a symlink, I create a backup ."
         sudo mv $HOME/bin bin_old && success "You can find your data here: $HOME/bin_old"
-        echo '"'
       else
-        echo '"'
-        info "I could not find data to backup."
-        echo '"'
+        fail "I could not find data to backup."
   fi
 }
 
 
 alex_Symlinks () {
 
-  echo '"' 
-  echo "Creating symlinks between the scc files, and the expected ones."
-  echo '"' 
+  success "Creating symlinks between the *.rc files, and the expected ones."
   
   ln -s $HOME/.dotfiles/bin $HOME/bin && success "symlinked: $HOME/bin ~> $HOME/.dotfiles/bin !"
 
@@ -229,23 +209,16 @@ alex_Symlinks () {
 
 
 alex_colors () {
-
-  echo '"' 
-  echo "Settin up a color schema for your tty."
-  echo '"' 
-
-  sudo gem install colorls
+  sudo gem install colorls &&  "Settin up a color schema for your tty."
 }
 
 
 alex_configFix () {
 
-    echo '"' 
     echo "Fixing .config permissions"
-    echo '"' 
 
   if ! [ -d "$HOME/.config" ]; then
-    "$HOME/.config doesn't exist" &2> dev/null
+    "$HOME/.config doesn't exist" > fail 2&> > dev/null
   else
     sudo chown $(whoami) $HOME/.config 
     success '.config permissions fixed'
@@ -253,45 +226,9 @@ alex_configFix () {
 }
 
 alex_fontSetup () {
-
-  echo '"' 
-  info 'I provide you a high quality font. ' 
-  echo '"' 
-
+  success 'I search a freaky font.. ' 
   cp $HOME/.dotfiles/Source\ Code\ Pro\ Nerd\ Font\ Complete.ttf /Library/Fonts
   success "You go the: SourceCodeProNerdFont font !"
-}
-
-backupBin
-alex_Symlinks
-alex_colors
-alex_fontSetup
-iterm_setup
-alex_itermConfig
-alex_configFix
-
-
-echo '"' 
-read -p "Should I set zsh to your default shell? y/n " -n 1 -r
-echo '"' 
-
-if [[ $REPLY =~ ^[Yy]$ ]] 
-  then
-    chsh -s /bin/zsh
-fi
-
-
-iterm_setup() {
-   
-    defaults write com.googlecode.iterm2 PrefsCustomFolder -string "$HOME/.itermcfg/"
-    defaults write com.googlecode.iterm2 LoadPrefsFromCustomFolder -bool true
-    
-      if [[ $? -eq 0 ]]
-      then
-          success "successfully configured iTerm2 to use my settings!"
-      else
-          echo "failed to apply my settings." >&2 >> dev/null;
-      fi
 }
 
 
@@ -302,14 +239,13 @@ alex_itermConfig () {
       then
     else 
 
-      echo '"'
-      read -p "I see you are already using iTerm2. Do you like to try my profile settings? y/n " -n 1 -r
-      echo '"'
+      success 'I see you are already using iTerm2.'
+      read -p " Do you like to try my profile settings? y/n " -n 1 -r
 
       if [[ $REPLY =~ ^[Yy]$ ]]
       then
 
-          defaults write com.googlecode.iterm2 PrefsCustomFolder -string "$HOME/.itermcfg/"
+          defaults write com.googlecode.iterm2 PrefsCustomFolder -string "$HOME/.itermcfg/" | success 2&> > dev/null
           defaults write com.googlecode.iterm2 LoadPrefsFromCustomFolder -bool true
 
           if [[ $? -eq 0 ]]
@@ -320,14 +256,14 @@ alex_itermConfig () {
           fi
       fi
 
-    echo '"'
-    echo 'Please choose a theme: '
-    info 'If you later want to try other ones, '
-    info '>   zshtheme:   and you can choose again! '
-    echo '"'
-
+    echo 'Please choose a theme: ' 
     options=("spaceship" "powerline10k" "powerlevel9k" "random")
-
+    
+    for theme in "${options[@]}"
+    do
+      echo theme > dev/null
+    done
+    
     select opt in "${options[@]}"
     do
         case $opt in
@@ -343,23 +279,50 @@ alex_itermConfig () {
             "random")
                 export ZSH_THEME="random";
                 ;;
-            *) echo "invalid option $REPLY";;
+            *) fail "invalid option $REPLY";;
         esac
     done
+    success 'Perfect choice !'
   fi  
 }
+
+iterm_setup() {
+   
+    defaults write com.googlecode.iterm2 PrefsCustomFolder -string "$HOME/.itermcfg/"
+    defaults write com.googlecode.iterm2 LoadPrefsFromCustomFolder -bool true
+    
+      if [[ $? -eq 0 ]]
+      then
+          success "Successfully configured iTerm2 to use my settings!"
+      else
+          fail "failed to apply my settings." >&2 >> dev/null;
+      fi
+}
+
+
+backupBin
+alex_Symlinks
+alex_colors
+alex_fontSetup
+iterm_setup
+alex_itermConfig
+alex_configFix
+
+
+read -p "Should I setup zsh as your default shell? y/n " -n 1 -r
+if [[ $REPLY =~ ^[Yy]$ ]] 
+  then
+    chsh -s /bin/zsh
+    success "Perfect !"
+fi
 
 
 if ! [ -f /Applications/iTerm2 ]; 
   then
-      echo '"' 
       success 'Badass macOS terminal installed!'
-      echo '"' 
-    return 0;
+    exit 0;
   else 
     ./Applications/iTerm2
-    echo '"' 
     success 'Badass macOS terminal installed!'
-    echo '"' 
-    return 0;
+    exit 0;
 fi
